### PR TITLE
J cords lps 75080

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-75080

I found that workflow on addUser sends a groupId of 0 from [here](https://github.com/liferay/liferay-portal/blob/2310a678cbad6751d422f43a0f0117fcac5edf9e/portal-kernel/src/com/liferay/portal/kernel/workflow/WorkflowHandlerRegistryUtil.java#L217-L219). I adjusted the code to use CompanyServiceSettingsLocator instead of the Group one. Everything seems to be working fine now.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:reopen

**Comment by joshuacords** [comment]
ci:retest

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Pull request submitted to https://github.com/liferay/com-liferay-portal-workflow/pull/212. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Thanks!

**Pull request merged**
