### PR TITLE
LPS-76086 escaping xml content to preserve format

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brandizzi** [comment]
Hey @linolaoj! These errors appear to be related to the fix. Can you confirm that please? Thanks!

**Comment by linolaoj** [comment]
@brandizzi , I'll check it out. Thanks!

**Comment by linolaoj** [comment]
Hi @brandizzi, I'm going to resend.
Thanks!

**Pull request closed without merging**
